### ISSUE TITLE
Somo on port 80

### ISSUE THREAD

**Issue by MangNPB** [didiatworkz/screenly-ose-monitoring#66]
My apology for posting the other post of related topic on pull request (github newbie!).

The reality: Screenly ose latest version will redirect all http request to https port 443. this means they are moving to more secure option and in a way abandoning port 80. 

The request: Can we make let end user access SOMO web UI easier by changing port 9000 to port 80. So if we run DNS locally we can allow end users to access SOMO with something short and simple like "Front.TV" on url rather than "Front.TV:9000"

the problem: Somo still seem to send API request to port 80 by default. But then Screenly ose redirect them to 443 anyway. So how can we force all API from SOMO to Screenly ose to go straight to 443 and leave port 80 to SOMO.

If that required a lot of recoding then how about we disable screenly ose 443 and put somo on 443?

Mang

**Comment by MangNPB** [comment]
some fiddling i was able to turn off OSE 443 and put SOMO on 443. the whole thing works and life is much easier to tell your end users to go on https rather than :9000. Hopefully your next update would have an option to force this with a simple toggle option. to change screenly.conf and monitoring.conf listen port with appropriate parameters..

**Comment by didiatworkz** [comment]
Hello @MangNPB 

Because of your previous problem: Don't worry - it can happen.

That sounds like an interesting solution, but I won't change the Screenlye OSE project - SOMO should really be able to run in parallel without affecting Screenly - hence port 9000, as nothing can get in the way with this port.

SOMO can also run on port 80 by default - SOMO detects whether a Screenly OSE is installed on the target system and then switches to port 9000 itself. If no Screenly OSE is installed, SOMO installs itself on port 80 (standalone installation) (Tested with Debian/Ubuntu Server).

Otherwise, you can change the port via this WIKI article: https://github.com/didiatworkz/screenly-ose-monitoring/wiki/Change-Port-9000-to-XX

HTTPS is currently still an issue - if Screenly OSE has been switched to HTTPS, everything should work with SOMO. This has been tested sufficiently from my side.
If SOMO is also to be able to use HTTPS (which I also prefer), then I still have to rebuild and learn a few things.
I will think about it.

Regards
didiatworkz
