### ISSUE TITLE
Change Display Settings

### ISSUE THREAD

**Issue by HunterZeroSix** [didiatworkz/screenly-ose-monitoring#68]
First of all, you have implemented a super project here. I also had the idea to create a script to manage Screenly OSE players. I would have built the whole thing just the other way around. As a client to server model. 
I also like your approach. 
The only disadvantage is that the players must be directly accessible. 

Long speech short sense. **Great project and nice that you share it with us.** 

Now to my concern.

# Change Display Settings

It would be super useful to change some Display Settings over SOMO.  
I know it's only used once, but then you don't have to manually connect to the Raspberry and change those settings.  

The following Settings would be nice.

## Display Oversan  

extractet from */boot/config.txt*  
```txt
# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1
```

## Display Rotation

https://pimylifeup.com/raspberry-pi-rotate-screen/

Changes on this file */boot/config.txt*, requires a reboot.

**Comment by didiatworkz** [comment]
Hello @HunterZeroSix 
Please excuse my delayed response - I have many to do currently.

Thanks for your Feedback 😄 
And thanks for your Ideas. I understand what you want, but that isn't the focus of my project to do this.
It is important to me that SOMO sticks remains separate from Screenly OSE and cannot be set on the system itself.
Therefore, SOMO controls everything via the official API of Screenly OSE. 
One could implement it with the help of SOMA. But so far, they only read information and do not change anything on the client.
I don't currently have the knowledge to programme this securely so that strangers can't simply change these settings on the device.

You will have no choice to implement this in your set-up process using bash script.

Regards,
didiatworkz

**Comment by HunterZeroSix** [comment]
Hello didiatworkz,

Thank you for your answer. 
I will write a script for my purposes. 

You can close the ticket.

Regards,
HunterZeroSix
